"""
Comprehensive security vendor/product list for autocomplete.
Sourced from market maps, analyst reports, vendor databases, YC portfolio,
RSAC Innovation Sandbox, GitHub awesome lists, MSSP Alert Top 250, and more.
Covers EDR, SIEM, cloud, identity, email, network, NDR, vulnerability
management, WAF, SOAR, DLP, GRC, pen testing, IoT/OT, privacy,
DevSecOps, zero trust, browser security, ASM, training, AI security,
MSSPs/MDR, data security, API security, supply chain, Kubernetes,
fraud/bot, digital forensics, security ratings, and more.
"""

VENDORS = [
    # --- EDR / XDR / Endpoint Protection ---
    "Acronis Cyber Protect",
    "Bitdefender",
    "Bitdefender GravityZone",
    "BlackBerry",
    "BlackBerry Cylance",
    "Carbon Black",
    "Cisco Secure Endpoint",
    "Comodo",
    "Comodo OpenEDR",
    "CrowdStrike",
    "CrowdStrike Falcon",
    "Cybereason",
    "Cynet",
    "Cynet 360",
    "Deep Instinct",
    "Elastic Security",
    "Emsisoft",
    "ESET",
    "ESET PROTECT",
    "F-Secure",
    "FortiEDR",
    "Fortinet FortiEDR",
    "Halcyon",
    "Huntress",
    "Kaspersky",
    "Kaspersky Endpoint Security",
    "Malwarebytes",
    "Malwarebytes ThreatDown",
    "McAfee",
    "Microsoft Defender for Endpoint",
    "Microsoft Defender XDR",
    "Norton",
    "Palo Alto Cortex XDR",
    "Cortex XDR",
    "RSA NetWitness XDR",
    "SentinelOne",
    "SentinelOne Singularity",
    "Sophos",
    "Sophos Intercept X",
    "Stellar Cyber",
    "Stellar Cyber Open XDR",
    "Symantec Endpoint Protection",
    "Tanium",
    "Trellix",
    "Trellix Endpoint Security",
    "Trend Micro",
    "Trend Micro Vision One",
    "VMware Carbon Black",
    "WatchGuard",
    "WatchGuard EPDR",
    "WithSecure",
    "WithSecure Elements",
    "Xcitium",
    "Xcitium EDR",

    # --- SIEM ---
    "AlienVault",
    "AlienVault OSSIM",
    "AT&T Cybersecurity",
    "Datadog Security",
    "Devo",
    "Devo SIEM",
    "Elastic SIEM",
    "Exabeam",
    "Exabeam Fusion",
    "FortiSIEM",
    "Fortinet FortiSIEM",
    "Google Chronicle",
    "Google Chronicle SIEM",
    "Graylog",
    "Hunters",
    "Hunters SIEM",
    "IBM QRadar",
    "IBM QRadar SIEM",
    "LogPoint",
    "LogRhythm",
    "LogRhythm SIEM",
    "ManageEngine Log360",
    "McAfee Enterprise Security Manager",
    "Microsoft Sentinel",
    "NetWitness",
    "New Relic",
    "OSSEC",
    "Panther",
    "Panther SIEM",
    "Rapid7 InsightIDR",
    "Securonix",
    "SIEMonster",
    "Splunk",
    "Splunk Enterprise Security",
    "Sumo Logic",
    "Sumo Logic Cloud SIEM",
    "USM Anywhere",
    "Wazuh",

    # --- Cloud Security / CSPM / CWPP / CNAPP ---
    "AccuKnox",
    "Aikido Security",
    "Aqua Security",
    "Aqua CSPM",
    "AWS Security Hub",
    "Bridgecrew",
    "Check Point CloudGuard",
    "CloudGuard",
    "CloudDefense.AI",
    "Cyscale",
    "Ermetic",
    "Fidelis Halo",
    "Fugue",
    "Google Cloud Security Command Center",
    "JupiterOne",
    "Lacework",
    "Lightspin",
    "Microsoft Defender for Cloud",
    "Orca Security",
    "Palo Alto Prisma Cloud",
    "Prisma Cloud",
    "Prowler",
    "Qualys TotalCloud",
    "Runecast",
    "ScoutSuite",
    "Snyk Cloud",
    "Sonrai Security",
    "Sysdig",
    "Sysdig Secure",
    "Tenable Cloud Security",
    "Upwind",
    "Upwind Security",
    "Uptycs",
    "Wiz",
    "Zscaler Posture Control",

    # --- Identity / IAM / PAM ---
    "Auth0",
    "Axiad",
    "BeyondTrust",
    "CyberArk",
    "CyberArk Privileged Access",
    "Delinea",
    "Delinea Secret Server",
    "Duo Security",
    "ForgeRock",
    "Foxpass",
    "HashiCorp Vault",
    "IBM Security Verify",
    "Imprivata",
    "JumpCloud",
    "Keeper Security",
    "ManageEngine ADManager",
    "Microsoft Entra ID",
    "miniOrange",
    "Okta",
    "OneIdentity",
    "One Identity",
    "OneLogin",
    "OneSpan",
    "Oracle Identity",
    "Ping Identity",
    "Ping Identity PingOne",
    "PingOne",
    "Sailpoint",
    "SailPoint",
    "SailPoint IdentityNow",
    "Saviynt",
    "Silverfort",
    "Strata Identity",
    "StrongDM",
    "Teleport",
    "Thales SafeNet",
    "Thycotic",
    "Transmit Security",
    "Veza",

    # --- Email Security ---
    "Abnormal Security",
    "Abnormal AI",
    "Area 1 Security",
    "Avanan",
    "Barracuda",
    "Barracuda Email Security",
    "Cisco Secure Email",
    "Clearswift",
    "Cloudflare Area 1",
    "Cofense",
    "Egress",
    "FireEye Email Security",
    "Forcepoint Email Security",
    "Harmony Email",
    "Hornetsecurity",
    "IRONSCALES",
    "Libraesva",
    "Material Security",
    "Microsoft Defender for Office 365",
    "Mimecast",
    "Perception Point",
    "Proofpoint",
    "Proofpoint Email Protection",
    "Retarus",
    "Sophos Email",
    "SpamTitan",
    "Sublime Security",
    "Symantec Email Security",
    "Tessian",
    "TitanHQ",
    "Trend Micro Email Security",
    "Trustifi",
    "Vade",
    "Vade Secure",
    "Vircom modusGate",
    "Virtru",
    "Zerospam",

    # --- Network Security / Firewall / NGFW ---
    "Barracuda CloudGen Firewall",
    "Cato Networks",
    "Check Point",
    "Check Point Quantum",
    "Cisco",
    "Cisco Firepower",
    "Cisco Meraki",
    "Cloudflare",
    "Cloudflare Magic WAN",
    "Corsa Security",
    "F5",
    "F5 BIG-IP",
    "FireMon",
    "Forcepoint",
    "Forcepoint NGFW",
    "Fortinet",
    "Fortinet FortiGate",
    "Hillstone Networks",
    "Huawei",
    "Juniper",
    "Juniper SRX",
    "Kemp Technologies",
    "Netskope",
    "Palo Alto Networks",
    "Palo Alto Networks NGFW",
    "pfSense",
    "SonicWall",
    "Sophos Firewall",
    "Stormshield",
    "Tufin",
    "Untangle",
    "Versa Networks",
    "WatchGuard Firebox",
    "Zscaler",
    "Zscaler Internet Access",
    "Zyxel",

    # --- NDR (Network Detection & Response) ---
    "Arista Networks NDR",
    "Corelight",
    "Darktrace",
    "ExtraHop",
    "ExtraHop Reveal(x)",
    "Fidelis Network",
    "Flowmon",
    "Gatewatcher",
    "Gigamon",
    "IronNet",
    "LinkShadow",
    "Lumu Technologies",
    "NIKSUN",
    "Plixer",
    "Progress Flowmon",
    "Sangfor",
    "Stamus Networks",
    "Vectra AI",
    "Vectra Cognito",
    "Zeek",

    # --- Vulnerability Management ---
    "Arctic Wolf",
    "Axonius",
    "BeyondTrust Retina",
    "CrowdStrike Falcon Spotlight",
    "Greenbone",
    "InsightVM",
    "Ivanti Neurons",
    "Lansweeper",
    "Microsoft Defender Vulnerability Management",
    "Nessus",
    "Nexpose",
    "OpenVAS",
    "Qualys",
    "Qualys VMDR",
    "Rapid7",
    "Rapid7 InsightVM",
    "SecPod SanerNow",
    "Tenable",
    "Tenable Nessus",
    "Tenable.io",
    "Tripwire",
    "Tripwire IP360",

    # --- Application Security / SAST / DAST / SCA ---
    "Acunetix",
    "Apiiro",
    "AppKnox",
    "Bandit",
    "Bearer",
    "Black Duck",
    "Bright Security",
    "Burp Suite",
    "Checkmarx",
    "Checkmarx SAST",
    "Checkmarx One",
    "CodeQL",
    "Contrast Security",
    "Coverity",
    "Cycode",
    "Dependabot",
    "Endor Labs",
    "Fortify",
    "GitHub Advanced Security",
    "GitLab Security",
    "GitLab Ultimate Security",
    "Grype",
    "HCL AppScan",
    "Invicti",
    "JFrog Xray",
    "Jit",
    "Jit Security",
    "Kodem",
    "Mend",
    "Mend.io",
    "Micro Focus Fortify",
    "Netsparker",
    "Oligo Security",
    "Orca AppSec",
    "OWASP ZAP",
    "OX Security",
    "PortSwigger",
    "Probely",
    "ReversingLabs",
    "Rezilion",
    "Semgrep",
    "ShiftLeft",
    "Snyk",
    "Snyk Code",
    "Snyk Open Source",
    "Socket",
    "SonarQube",
    "SonarCloud",
    "SonarSource",
    "Sonatype",
    "Sonatype Nexus",
    "StackHawk",
    "Synopsys",
    "Veracode",
    "WhiteSource",

    # --- WAF / API Security ---
    "42Crunch",
    "Akamai",
    "Akamai Kona Site Defender",
    "Akamai App & API Protector",
    "AWS WAF",
    "Azure WAF",
    "Cloudflare WAF",
    "Cequence Security",
    "Coraza WAF",
    "F5 Advanced WAF",
    "Fastly",
    "Fastly Signal Sciences",
    "Google Cloud Armor",
    "Imperva",
    "Imperva WAF",
    "Indusface",
    "Kong",
    "ModSecurity",
    "Noname Security",
    "Prophaze",
    "Radware",
    "Reblaze",
    "Salt Security",
    "Signal Sciences",
    "Sucuri",
    "Sucuri WAF",
    "Traceable AI",
    "ThreatX",
    "Wallarm",
    "Wallarm API Security",
    "Wordfence",

    # --- SOAR ---
    "Blink",
    "Blink Ops",
    "Cyware",
    "D3 Security",
    "Fortinet FortiSOAR",
    "Google Siemplify",
    "Hive",
    "IBM Resilient",
    "LogicHub",
    "Palo Alto XSOAR",
    "Cortex XSOAR",
    "Rapid7 InsightConnect",
    "Resolve",
    "ServiceNow Security Operations",
    "Shuffle Automation",
    "Shuffle SOAR",
    "Siemplify",
    "Splunk SOAR",
    "Swimlane",
    "TheHive",
    "Tines",
    "Torq",

    # --- DLP (Data Loss Prevention) ---
    "Code42",
    "CoSoSys Endpoint Protector",
    "Cyberhaven",
    "Digital Guardian",
    "Dtex Systems",
    "Forcepoint DLP",
    "GTB Technologies",
    "Kitecyber",
    "McAfee DLP",
    "Microsoft Purview",
    "Microsoft Purview DLP",
    "Netskope DLP",
    "Nightfall AI",
    "Proofpoint DLP",
    "Safetica",
    "SecureTrust DLP",
    "Spirion",
    "Strac",
    "Symantec DLP",
    "Teramind",
    "Trellix DLP",
    "Zecurion",
    "Zscaler DLP",

    # --- Endpoint Management / UEM ---
    "Automox",
    "Fleet",
    "Hexnode",
    "Ivanti",
    "Jamf",
    "Kandji",
    "ManageEngine Desktop Central",
    "ManageEngine Endpoint Central",
    "Microsoft Intune",
    "Mosyle",
    "NinjaOne",
    "NinjaRMM",
    "VMware Workspace ONE",

    # --- Threat Intelligence ---
    "Anomali",
    "Anomali ThreatStream",
    "Censys",
    "CrowdStrike Falcon Intelligence",
    "Cyble",
    "DeCYFIR",
    "DomainTools",
    "EclecticIQ",
    "Flare",
    "Flare Security",
    "Flashpoint",
    "GreyNoise",
    "Group-IB",
    "Intel 471",
    "Intel471",
    "Intezer",
    "LookingGlass Cyber Solutions",
    "Mandiant",
    "Mandiant Advantage",
    "MISP",
    "OpenCTI",
    "Recorded Future",
    "RiskIQ",
    "SecurityTrails",
    "Shodan",
    "SOCRadar",
    "SpyCloud",
    "ThreatBook",
    "ThreatConnect",
    "ThreatQuotient",
    "ThreatStream",
    "VirusTotal",
    "ZeroFox",

    # --- Backup / Disaster Recovery ---
    "Acronis",
    "Acronis Cyber Protect Cloud",
    "Arcserve",
    "Axcient",
    "Backblaze",
    "Carbonite",
    "Cohesity",
    "Commvault",
    "Datto",
    "Druva",
    "HYCU",
    "Nakivo",
    "Rubrik",
    "Unitrends",
    "Veeam",
    "Veritas",
    "Zerto",

    # --- GRC / Compliance / Audit ---
    "A-LIGN",
    "Anecdotes",
    "Archer",
    "AuditBoard",
    "Centraleyes",
    "Coalfire Compliance",
    "Compliance.ai",
    "Compyl",
    "Conveyor",
    "Cority",
    "CyberSaint",
    "Diligent",
    "Drata",
    "Galvanize",
    "Hyperproof",
    "Laika",
    "LogicGate",
    "MetricStream",
    "OneTrust",
    "ProcessUnity",
    "Reciprocity ZenGRC",
    "RegScale",
    "Resolver",
    "Riskonnect",
    "RSAM",
    "RSA Archer",
    "SafeBase",
    "SAI360",
    "Scrut",
    "Scrut Automation",
    "Scytale",
    "Secureframe",
    "ServiceNow GRC",
    "SimpleRisk",
    "Sprinto",
    "StandardFusion",
    "Strike Graph",
    "Thoropass",
    "TrustCloud",
    "TrustMAPP",
    "Tugboat Logic",
    "Vanta",
    "ZenComply",
    "ZenGRC",

    # --- Pen Testing / Red Team / Breach & Attack Simulation ---
    "AttackIQ",
    "Bugcrowd",
    "Cobalt",
    "Cobalt.io",
    "Cobalt Strike",
    "Core Impact",
    "Cymulate",
    "HackerOne",
    "Horizon3.ai",
    "NodeZero",
    "Mandiant Red Team",
    "Metasploit",
    "NetSPI",
    "Pentera",
    "PlexTrac",
    "Randori",
    "Rapid7 Metasploit",
    "SafeBreach",
    "Scythe",
    "Synack",
    "XM Cyber",

    # --- CASB ---
    "Bitglass",
    "Cisco Cloudlock",
    "Lookout CASB",
    "Lookout",
    "Microsoft Defender for Cloud Apps",
    "Netskope CASB",
    "Skyhigh Security",
    "Zscaler CASB",

    # --- IoT / OT / ICS Security ---
    "ABB Cybersecurity",
    "Armexa",
    "Armis",
    "Claroty",
    "CyberX",
    "Dragos",
    "Exein",
    "Forescout",
    "Fortinet OT Security",
    "Honeywell OT Cybersecurity",
    "Industrial Defender",
    "Kaspersky Industrial CyberSecurity",
    "Medigate",
    "Mission Secure",
    "Nozomi Networks",
    "OPSWAT",
    "Otorio",
    "Radiflow",
    "Rockwell Automation Cybersecurity",
    "Schneider Electric Cybersecurity",
    "SCADAfence",
    "Siemens Cybersecurity",
    "TXOne Networks",
    "Verve Industrial",
    "Waterfall Security",

    # --- Privacy / Data Protection ---
    "BigID",
    "Cookiebot",
    "CookieYes",
    "DataGrail",
    "Ethyca",
    "Informatica Data Privacy",
    "iubenda",
    "Ketch",
    "OneTrust Privacy",
    "Osano",
    "Privacera",
    "Privado",
    "Securiti",
    "Securiti.ai",
    "Termly",
    "Transcend",
    "TrustArc",
    "WireWheel",

    # --- DevSecOps / Container / Kubernetes Security ---
    "Anchore",
    "Aqua Security Trivy",
    "Armo",
    "ARMO Kubescape",
    "Bridgecrew Checkov",
    "Chainguard",
    "Falco",
    "Fairwinds",
    "Harness",
    "Isovalent",
    "KubeArmor",
    "Lacework Container Security",
    "NeuVector",
    "Portshift",
    "Prisma Cloud Compute",
    "Slim.ai",
    "Snyk Container",
    "StackRox",
    "Sysdig Falco",
    "Tigera",
    "Trivy",
    "Twistlock",

    # --- Zero Trust / ZTNA / SASE ---
    "Absolute",
    "Akamai Enterprise Application Access",
    "Appgate",
    "Axis Security",
    "Banyan Security",
    "Cato Networks SASE",
    "Cisco Duo",
    "Cloudflare Access",
    "Cloudflare One",
    "Cloudflare Zero Trust",
    "Forcepoint ONE",
    "Fortinet FortiSASE",
    "Google BeyondCorp",
    "Illumio",
    "InstaSafe",
    "Netskope SASE",
    "Palo Alto Prisma Access",
    "Perimeter 81",
    "Skyhigh Security SASE",
    "Tailscale",
    "Twingate",
    "Versa SASE",
    "VMware SASE",
    "Zscaler Private Access",
    "Zscaler SASE",

    # --- Browser Security ---
    "Authentic8 Silo",
    "Conceal",
    "Island",
    "Menlo Security",
    "Seraphic",
    "Talon Cyber Security",

    # --- Attack Surface Management / Exposure Management ---
    "Assetnote",
    "Bishop Fox Cosmos",
    "BitSight",
    "CyCognito",
    "Halo Security",
    "Mandiant ASM",
    "Microsoft Defender EASM",
    "Palo Alto Cortex Xpanse",
    "Cortex Xpanse",
    "Randori Recon",
    "Rapid7 InsightConnect ASM",
    "RiskIQ (Microsoft)",
    "Runzero",
    "SecurityScorecard",
    "Sevco Security",
    "UpGuard",

    # --- Security Awareness Training ---
    "Adaptive Security",
    "Cofense PhishMe",
    "Curricula",
    "CybSafe",
    "Hook Security",
    "Hoxhunt",
    "Infosec IQ",
    "Infosec Institute",
    "KnowBe4",
    "Living Security",
    "MetaCompliance",
    "Mimecast Awareness Training",
    "Ninjio",
    "PhishingBox",
    "Proofpoint Security Awareness",
    "SafeTitan",
    "SANS Security Awareness",
    "Terranova Security",
    "Wizer",
    "Wombat Security",

    # --- MDR / Managed Security ---
    "Accenture Security",
    "Arctic Wolf MDR",
    "AT&T Managed Security",
    "Binary Defense",
    "Blackpoint Cyber",
    "BlueVoyant",
    "CrowdStrike Falcon Complete",
    "Deloitte Cyber",
    "eSentire",
    "Expel",
    "IBM Managed Security",
    "KPMG Cyber",
    "Mandiant MDR",
    "Masergy",
    "NTT Security",
    "Optiv",
    "Proficio",
    "PwC Cyber",
    "Red Canary",
    "Secureworks",
    "Secureworks Taegis",
    "Sophos MDR",
    "TrustWave",
    "Trustwave",

    # --- PAM (Privileged Access Management) ---
    "Arcon",
    "BeyondTrust Privileged Access",
    "Centrify",
    "CyberArk PAM",
    "Delinea Privilege Manager",
    "Devolutions",
    "Ekran System",
    "FUDO Security",
    "Iraje",
    "ManageEngine PAM360",
    "Netwrix Privilege Secure",
    "Senhasegura",
    "Thycotic Secret Server",
    "Wallix",
    "Xceedium",

    # --- Secure Access Service Edge / SD-WAN ---
    "Aryaka",
    "Bigleaf Networks",
    "Cisco SD-WAN",
    "Citrix SD-WAN",
    "Cradlepoint",
    "FatPipe",
    "HPE Aruba EdgeConnect",
    "Open Systems SASE",
    "Peplink",
    "Silver Peak",
    "VMware SD-WAN",

    # --- Data Security / Database Security ---
    "Baffle",
    "Comforte AG",
    "Concentric AI",
    "Cyera",
    "Dasera",
    "Dig Security",
    "Guardium",
    "Immuta",
    "IBM Guardium",
    "Laminar",
    "Normalyze",
    "Open Raven",
    "Satori",
    "Sentra",
    "Sotero",
    "Symmetry Systems",
    "Thales CipherTrust",
    "Theom",
    "TokenEx",
    "Varonis",
    "Virtru Data Protection",
    "Voltage SecureData",
    "Vormetric",

    # --- Deception Technology ---
    "Acalvio",
    "Attivo Networks",
    "CounterCraft",
    "Fidelis Deception",
    "Illusive Networks",
    "PacketViper",
    "TrapX Security",
    "Zscaler Deception",

    # --- Microsegmentation ---
    "Akamai Guardicore",
    "ColorTokens",
    "Elisity",
    "Guardicore",
    "Illumio Core",
    "TrueFort",
    "VMware NSX",
    "Zero Networks",

    # --- DNS Security ---
    "Akamai DNS Security",
    "BlueCat",
    "Cisco Umbrella",
    "Cloudflare DNS",
    "DNSFilter",
    "EfficientIP",
    "Infoblox",
    "Infoblox BloxOne",
    "Neustar UltraDNS",
    "Nominum",
    "Quad9",
    "Webroot DNS Protection",

    # --- Secure Web Gateway ---
    "Cisco Secure Web Appliance",
    "ContentKeeper",
    "Forcepoint SWG",
    "iboss",
    "McAfee Web Gateway",
    "Menlo Security SWG",
    "Netskope SWG",
    "Symantec Web Security",
    "Zscaler SWG",

    # --- Mobile Security ---
    "Appdome",
    "Corrata",
    "Jamf Protect",
    "Lookout Mobile Security",
    "MobileIron",
    "NowSecure",
    "Pradeo",
    "Samsung Knox",
    "Wandera",
    "Zimperium",

    # --- ITDR (Identity Threat Detection & Response) ---
    "CrowdStrike Falcon Identity Threat Protection",
    "Microsoft Defender for Identity",
    "Oort",
    "Proofpoint Identity Threat Defense",
    "Quest Security",
    "Semperis",
    "Silverfort ITDR",
    "Tenable.ad",

    # --- Supply Chain Security ---
    "Apiiro Supply Chain",
    "Arnica",
    "Chainguard Images",
    "Cybeats",
    "EdgeBit",
    "FOSSA",
    "Legit Security",
    "Lineaje",
    "Manifest",
    "Phylum",
    "Scribe Security",
    "Sigstore",
    "Socket Supply Chain",
    "Tidelift",

    # --- Secrets Management ---
    "1Password",
    "1Password Business",
    "1Password for Teams",
    "Akeyless",
    "AWS Secrets Manager",
    "Azure Key Vault",
    "BeyondTrust Password Safe",
    "Bitwarden",
    "Conjur",
    "CyberArk Conjur",
    "Dashlane",
    "Doppler",
    "Enpass",
    "Google Secret Manager",
    "HashiCorp Vault Secrets",
    "Keeper",
    "Keeper Secrets Manager",
    "LastPass",
    "LastPass Business",
    "NordPass",
    "Passbolt",
    "Proton Pass",
    "RoboForm",
    "Thales Luna HSM",
    "Zoho Vault",

    # --- Security Validation / Continuous Testing ---
    "Beagle Security",
    "Bugcrowd Platform",
    "Coalfire",
    "Cobalt Pentest",
    "HackerOne Platform",
    "Horizon3.ai NodeZero",
    "Luta Security",
    "Pentera Platform",
    "Praetorian",
    "Picus Security",
    "Ridge Security",
    "SafeBreach Platform",
    "Synack Red Team",

    # --- Encryption / PKI / Certificate Management ---
    "AppViewX",
    "Comodo Certificate Manager",
    "DigiCert",
    "Entrust",
    "GlobalSign",
    "Keyfactor",
    "Let's Encrypt",
    "PrimeKey",
    "Sectigo",
    "Smallstep",
    "SSL.com",
    "Thales HSM",
    "Venafi",

    # --- Log Management / Observability ---
    "Chronosphere",
    "Cribl",
    "Cribl Stream",
    "Datadog",
    "Grafana",
    "Honeycomb",
    "Humio",
    "LogDNA",
    "Mezmo",
    "Observe Inc",
    "PagerDuty",
    "Papertrail",
    "Scalyr",
    "Seq",
    "Splunk Observability",

    # --- Fraud Prevention / Bot Management ---
    "Akamai Bot Manager",
    "Arkose Labs",
    "BioCatch",
    "Castle",
    "Cloudflare Bot Management",
    "DataDome",
    "DataVisor",
    "Deduce",
    "Featurespace",
    "Feedzai",
    "Fingerprint",
    "Forter",
    "hCaptcha",
    "HUMAN Security",
    "Kasada",
    "Kount",
    "PerimeterX",
    "reCAPTCHA",
    "Riskified",
    "Shape Security",
    "Shape (F5)",
    "Sift",
    "Socure",
    "ThreatMetrix",
    "TransUnion TruValidate",

    # --- Cloud Infrastructure Entitlement Management (CIEM) ---
    "Authomize",
    "Britive",
    "CloudKnox",
    "CrowdStrike CIEM",
    "Microsoft Entra Permissions",
    "Orca CIEM",
    "Permiso",
    "Sonrai CIEM",
    "Wiz CIEM",
    "Zilla Security",

    # --- Secure File Transfer / MFT ---
    "Accellion",
    "Axway",
    "Citrix ShareFile",
    "GoAnywhere MFT",
    "Kiteworks",
    "MOVEit",
    "Progress MOVEit",

    # --- Governance / Risk Quantification ---
    "Axio",
    "BitSight Technologies",
    "Brinqa",
    "C2M2",
    "Kovrr",
    "Panorays",
    "ProcessBolt",
    "RiskLens",
    "Safe Security",
    "SecurityScorecard Platform",
    "UpGuard BreachSight",

    # --- Third-Party Risk Management ---
    "Black Kite",
    "CyberGRX",
    "OneTrust Vendorpedia",
    "Panorays TPRM",
    "Prevalent",
    "ProcessUnity TPRM",
    "RiskRecon",
    "SecurityScorecard TPRM",
    "Whistic",

    # --- Security Questionnaire Automation ---
    "Conveyor Questionnaire",
    "Loopio",
    "OneTrust Athena",
    "Responsive",
    "SafeBase Trust Center",
    "Vanta Questionnaire",
    "Whistic Questionnaire",

    # --- Open Source Security Tools ---
    "Aircrack-ng",
    "Autopsy",
    "Bettercap",
    "Burp Suite Community",
    "ClamAV",
    "Fail2Ban",
    "Ghidra",
    "GoPhish",
    "GRR Rapid Response",
    "hashcat",
    "Hydra",
    "John the Ripper",
    "Kali Linux",
    "Lynis",
    "Maltego",
    "Metasploit Framework",
    "Nmap",
    "Nuclei",
    "OpenSCAP",
    "OpenVAS Scanner",
    "osquery",
    "OSSEC HIDS",
    "Responder",
    "Snort",
    "Suricata",
    "tcpdump",
    "Velociraptor",
    "Wireshark",
    "YARA",

    # --- AI Security / LLM Security ---
    "Arthur AI",
    "CalypsoAI",
    "Charm Security",
    "Clearly AI",
    "Cranium AI",
    "Cygeniq",
    "DeepKeep",
    "DeepTrust",
    "Golf AI Security",
    "Geordie AI",
    "HiddenLayer",
    "Lakera",
    "Lasso Security",
    "LLM Guard",
    "Noma Security",
    "Pangea",
    "Prompt Security",
    "Protect AI",
    "Realm Labs",
    "Reality Defender",
    "Rebuff AI",
    "Robust Intelligence",
    "SAIF CHECK",
    "Tinfoil Security",
    "Token Security",
    "ZeroPath",

    # --- Security Service Edge ---
    "Citrix SSE",
    "Forcepoint SSE",
    "Netskope SSE",
    "Palo Alto Prisma SASE",
    "Skyhigh SSE",
    "Zscaler SSE",

    # --- Digital Forensics / Incident Response ---
    "AccessData FTK",
    "Autopsy Forensic",
    "Belkasoft",
    "Binalyze",
    "Cado Security",
    "Cellebrite",
    "CrowdStrike Falcon Forensics",
    "EnCase",
    "Exterro",
    "Magnet Forensics",
    "OpenText EnCase",
    "Oxygen Forensics",
    "Paraben",
    "Volatility",
    "X-Ways Forensics",

    # --- Secure Communications ---
    "Abnormal Security ICES",
    "BlackBerry SecuSUITE",
    "Element (Matrix)",
    "Keybase",
    "Mimecast S2",
    "PreVeil",
    "Signal Enterprise",
    "Silent Circle",
    "Wickr",
    "Wire",

    # --- API Gateway / API Management ---
    "Apigee",
    "AWS API Gateway",
    "Azure API Management",
    "Kong Gateway",
    "MuleSoft",
    "Tyk",

    # --- DSPM (Data Security Posture Management) ---
    "BigID DSPM",
    "Cyera DSPM",
    "Dig Security DSPM",
    "Flow Security",
    "Normalyze DSPM",
    "Polar Security",
    "Sentra DSPM",
    "Symmetry Systems DSPM",
    "Varonis DSPM",
    "Wiz DSPM",

    # --- Cyber Insurance ---
    "At-Bay",
    "Aura",
    "Coalition",
    "Corvus Insurance",
    "Cowbell Cyber",
    "Resilience Cyber Insurance",
    "Telivy",

    # --- Miscellaneous / Multi-Category ---
    "Broadcom",
    "Dell Technologies",
    "Google Cloud Security",
    "HackerOne Bounties",
    "Hewlett Packard Enterprise",
    "Herjavec Group",
    "Kyndryl",
    "Leidos",
    "ManageEngine",
    "Micro Focus",
    "Microsoft Security",
    "NCC Group",
    "Palo Alto Networks Unit 42",
    "Rapid7 Platform",
    "Raytheon Cyber",
    "ReliaQuest",
    "RSA Security",
    "Schneider Electric",
    "SecureAuth",
    "SecureWorks",
    "Siemens",
    "Sophos Central",
    "Symantec",
    "Thales",
    "Unisys Stealth",
    "Upstream Security",
    "Verint",
    "Webroot",
    "Zimperium MAPS",

    # --- Security Operations / SOC Platforms ---
    "Blumira",
    "Chronicle SecOps",
    "Cotool",
    "Cyware Fusion",
    "InsightIDR",
    "LogicHub SOAR+",
    "ReliaQuest GreyMatter",
    "Respond Software",
    "Revelstoke",
    "SecOps Solution",
    "Siemplify SOAR",

    # --- Phishing Simulation ---
    "GoPhish Simulation",
    "King Phisher",
    "Lucy Security",
    "PhishER",
    "Proofpoint Phishing Simulation",
    "Sophos Phish Threat",

    # --- Network Access Control (NAC) ---
    "Aruba ClearPass",
    "Cisco ISE",
    "Extreme Networks",
    "Forescout NAC",
    "FortiNAC",
    "Portnox",
    "Pulse Secure",

    # --- DDoS Protection ---
    "Akamai Prolexic",
    "AWS Shield",
    "Azure DDoS Protection",
    "Cloudflare DDoS",
    "Corero",
    "F5 Silverline",
    "Imperva DDoS",
    "Neustar DDoS",
    "Radware DDoS",
    "Sucuri DDoS",

    # --- Quantum-Safe / Post-Quantum ---
    "ISARA",
    "PQShield",
    "Quantinuum",
    "QuSecure",
    "SandboxAQ",

    # --- SBOM (Software Bill of Materials) ---
    "Anchore SBOM",
    "FOSSA SBOM",
    "Manifest Cyber",
    "Mend SBOM",
    "Rezilion SBOM",
    "SPDX",
    "Syft",
    "Tidelift SBOM",

    # --- Insider Threat ---
    "Code42 Incydr",
    "DTEX InTERCEPT",
    "Ekran System Insider",
    "Gurucul",
    "ObserveIT",
    "Proofpoint ITM",
    "Securonix UEBA",
    "Teramind Insider Threat",
    "Veriato",

    # --- Secure Remote Access / VPN ---
    "Check Point VPN",
    "Cisco AnyConnect",
    "Citrix Gateway",
    "F5 Access",
    "Fortinet FortiClient",
    "GlobalProtect",
    "Ivanti Connect Secure",
    "NordLayer",
    "NordVPN",
    "OpenVPN",
    "Palo Alto GlobalProtect",
    "WireGuard",

    # --- Kubernetes / Container Runtime Security ---
    "Aqua kube-bench",
    "Calico",
    "Cilium",
    "Falco Runtime",
    "KubeLinter",
    "Kubescape",
    "Mondoo",
    "Prisma Cloud Container",
    "Sysdig Runtime",
    "Wiz Runtime Sensor",

    # --- Security for SaaS ---
    "Adaptive Shield",
    "AppOmni",
    "DoControl",
    "Grip Security",
    "Nudge Security",
    "Obsidian Security",
    "Reco",
    "SaaS Alerts",
    "Savvy Security",
    "SpinOne",
    "Suridata",
    "Valence Security",
    "Wing Security",

    # --- Unified Endpoint Security ---
    "Absolute Resilience",
    "CrowdStrike Falcon Go",
    "Microsoft Defender for Business",
    "Sophos Central Endpoint",
    "ThreatLocker",

    # --- Infrastructure as Code (IaC) Security ---
    "Accurics",
    "Bridgecrew Checkov IaC",
    "Checkov",
    "Indeni Cloudrail",
    "KICS",
    "Snyk IaC",
    "Terraform Sentinel",
    "tfsec",

    # --- Cloud Workload Protection ---
    "Aqua Cloud Native Security",
    "CrowdStrike Cloud Security",
    "Deep Security",
    "Illumio CloudSecure",
    "Kaspersky Hybrid Cloud Security",
    "Trend Micro Cloud One",

    # --- Security Analytics / UEBA ---
    "Adlumin",
    "Exabeam Advanced Analytics",
    "Gurucul UEBA",
    "Microsoft Sentinel UEBA",
    "Securonix Next-Gen SIEM",
    "Splunk UBA",

    # --- Code Signing ---
    "DigiCert Code Signing",
    "Entrust Code Signing",
    "Keyfactor SignServer",
    "SignPath",
    "Venafi CodeSign Protect",

    # --- Hardware Security ---
    "Thales Luna Network HSM",
    "Utimaco",
    "YubiKey",
    "Yubico",

    # --- MSSP / SOCaaS ---
    "Alert Logic",
    "Assura",
    "Avertium",
    "Clearwater Security",
    "ConnectWise",
    "Critical Start",
    "Deepwatch",
    "Field Effect",
    "Fortinet FortiGuard",
    "MAD Security",
    "M.A. Polce",
    "Netsurion",
    "Nuspire",
    "Open Systems",
    "Paranet Solutions",
    "Perch Security",
    "TechOnPurpose",
    "Todyl",
    "UnderDefense",
    "Vigilance MDR",

    # --- Penetration Testing Platforms ---
    "Core Security",
    "Immuniweb",
    "Intruder",
    "Invicti Acunetix",
    "Nikto",
    "Pentest-Tools.com",
    "Qualys WAS",
    "SQLmap",
    "Tenable.io WAS",

    # --- Cloud Access Security ---
    "Ciphercloud",
    "McAfee MVISION Cloud",
    "Microsoft Cloud App Security",
    "Skyhigh CASB",

    # --- Security Ratings ---
    "BitSight Security Ratings",
    "RiskRecon Ratings",
    "SecurityScorecard Ratings",
    "UpGuard Security Ratings",

    # --- Threat Hunting ---
    "Cyborg Security",
    "EclecticIQ Platform",
    "KELA",
    "Polarity",
    "Team Cymru",
    "ThreatBook Hunting",

    # --- Risk-Based Vulnerability Management ---
    "Brinqa Platform",
    "Kenna Security",
    "NopSec",
    "Nucleus Security",
    "Vulcan Cyber",

    # --- OT-specific ---
    "Bayshore Networks",
    "Fortinet FortiGate Rugged",
    "Honeywell Forge",
    "Phoenix Contact",
    "Tofino Security",

    # --- Automotive Cybersecurity ---
    "Argus Cyber Security",
    "C2A Security",
    "Karamba Security",
    "PlaxidityX",
    "Upstream Security Automotive",

    # --- Space / Satellite Cybersecurity ---
    "SpiderOak",

    # --- Compliance-Specific ---
    "Coalfire",
    "Delve",
    "Delve Compliance",
    "Delve Labs",
    "Delve Risk",
    "Delve Security",

    # --- RSAC Innovation Sandbox Companies (Historical) ---
    "Humanix",
    "ProjectDiscovery",

    # --- YC Security Companies ---
    "Alacrity",
    "Keyri",
    "Multifactor",
    "Oneleet",

    # --- Additional AI Security & AI-Adjacent ---
    "Averlon",
    "Coro",
    "Coro Security",
    "Darktrace AI",
    "Dazz",
    "Endor Labs Security",
    "Enso Security",
    "Eureka Security",
    "Gutsy",
    "Latio Tech",
    "Legit Security Platform",
    "Myrror Security",
    "NorthStar AI",
    "Opus Security",
    "Oxeye",
    "Phoenix Security",
    "Piiano",
    "Plexicus",
    "Polar Security Platform",
    "Rezonate",
    "Riscosity",
    "Seemplicity",
    "Silk Security",
    "Simbian",
    "Sweet Security",
    "Torq AI",
    "Tuskira",
    "Uptycs Cloud",
    "Vulcan Cyber Platform",

    # --- Additional Open Source Tools ---
    "Amass",
    "BloodHound",
    "Caldera",
    "Cuckoo Sandbox",
    "Dnsrecon",
    "Empire",
    "EvilGinx",
    "Gitleaks",
    "Hashcat",
    "httpx",
    "Impacket",
    "LinPEAS",
    "MobSF",
    "Ncrack",
    "OpenCTI Platform",
    "OpenDLP",
    "OSSIM",
    "PowerSploit",
    "Prowler Cloud",
    "Recon-ng",
    "SecLists",
    "Seatbelt",
    "SpiderFoot",
    "Subfinder",
    "TheHive Platform",
    "TruffleHog",
    "Viper Framework",
    "WinPEAS",
    "Wpscan",
    "ZAP",

    # --- Additional Network Tools ---
    "Bro",
    "Cacti",
    "LibreNMS",
    "Nagios",
    "PRTG",
    "SolarWinds",
    "SolarWinds Network",
    "Zabbix",

    # --- Additional Pen Testing / Offensive Tools ---
    "BeEF",
    "Dirb",
    "DirBuster",
    "Enum4linux",
    "Ettercap",
    "Fierce",
    "Gobuster",
    "Masscan",
    "MITMProxy",
    "Netcat",
    "Nikto Scanner",
    "Powershell Empire",
    "RouterSploit",
    "SET (Social Engineering Toolkit)",
    "Shodan CLI",
    "THC Hydra",
    "w3af",
    "WFuzz",
    "XSSer",

    # --- Additional Backup / Recovery ---
    "Arcserve UDP",
    "Bacula",
    "Clumio",
    "Comet Backup",
    "Cove Data Protection",
    "CrashPlan",
    "iDrive",
    "N-able Backup",
    "Wasabi",

    # --- Additional Cloud Security Vendors ---
    "Aqua Trivy",
    "Brainframe",
    "CloudPassage",
    "Dome9",
    "Fidelis Cybersecurity",
    "Hillstone CloudHive",
    "InsightCloudSec",
    "Menlo Security Cloud",
    "Netacea",
    "NetScout",
    "Orca Cloud",
    "PingSafe",
    "Saviynt Cloud",
    "SecureKloud",
    "Skyhigh Cloud",
    "Sysdig Cloud",
    "Tenable.cs",
    "Turbot",
    "Wiz Cloud",

    # --- Additional Identity / Access Vendors ---
    "Aembit",
    "Astrix Security",
    "Authelia",
    "Authentik",
    "Cerby",
    "ClearSky",
    "Clutch Security",
    "Descope",
    "Frontegg",
    "Gluu",
    "Grip Identity",
    "IDnow",
    "IndyKite",
    "Keyless",
    "LoginRadius",
    "Oasis Security",
    "Oso",
    "Stytch",
    "SuperTokens",
    "WorkOS",

    # --- Additional Email / Messaging Security ---
    "AnubisNetworks",
    "Armorblox",
    "Censornet",
    "Graphus",
    "Guardz",
    "Inky",
    "MailGuard",
    "PhishLabs",
    "SlashNext",
    "SpamExperts",
    "Valimail",
    "Xorlab",

    # --- Additional Data Security / Privacy ---
    "Borneo",
    "Collibra",
    "Duality Technologies",
    "Evervault",
    "Ground Labs",
    "Integral",
    "Metomic",
    "MineOS",
    "Skyflow",
    "Seclore",
    "Thales Data Protection",
    "Tokenvault",
    "Vera",
    "Very Good Security",
    "Zettaset",

    # --- Additional API Security ---
    "Akamai API Security",
    "APIsec",
    "Apiiro API",
    "Apoxy",
    "Corsha",
    "FireTail",
    "Gravitee",
    "Imperva API Security",
    "Levo",
    "Neosec",
    "Osa Security",
    "Ping API Security",
    "Pynt",
    "Resurface",
    "Treblle",
    "Wib",

    # --- Additional Supply Chain Security ---
    "Anchore Enterprise",
    "Aqua Supply Chain",
    "Codenotary",
    "Deepfactor",
    "Debricked",
    "Grammatech",
    "Harden Runner",
    "Jit Supply Chain",
    "Kusari",
    "Snyk Supply Chain",
    "Step Security",
    "Testifysec",
    "Tromzo",

    # --- Additional Kubernetes / Container ---
    "Alcide",
    "Aporeto",
    "Aqua Enforcer",
    "Cast AI",
    "Deepfence",
    "Kubecost",
    "Loft Labs",
    "Nirmata",
    "Otterize",
    "Oxeye Security",
    "Rad Security",
    "Spyderbat",
    "Vali Cyber",

    # --- Additional Privacy / Consent Tools ---
    "Cassie",
    "Clym",
    "Consentmanager",
    "Crownpeak",
    "Didomi",
    "Enzuzo",
    "Hushly",
    "Ketch Privacy",
    "Onetrust CookieConsent",
    "OneTrust Consent",
    "Piwik PRO",
    "Segment",
    "Sourcepoint",
    "Truendo",
    "Usercentrics",

    # --- Additional Fraud / Identity Verification ---
    "Alloy",
    "Callsign",
    "Ekata",
    "Emailage",
    "Jumio",
    "Mitek",
    "Onfido",
    "Persona",
    "Plaid",
    "Sardine",
    "Shufti Pro",
    "Sumsub",
    "Telesign",
    "Trulioo",
    "Veriff",

    # --- Additional Digital Forensics ---
    "ADF Digital Forensics",
    "Arsenal Recon",
    "Axiom Cyber",
    "BlackBag",
    "Detego",
    "Elcomsoft",
    "Forensic Explorer",
    "Griffeye",
    "Intella",
    "MacQuisition",
    "MD5",
    "MSAB",
    "Nuix",
    "Paladin Forensics",
    "PassMark OSForensics",
    "Sleuth Kit",
    "Sumuri",
    "Xplico",

    # --- Additional Security Ratings / Risk ---
    "Black Kite Platform",
    "ClickArmor",
    "Cyentia",
    "Findings",
    "OneTrust Risk",
    "ProcessBolt Risk",
    "Quantivate",
    "Resolver Risk",
    "RiskSense",
    "ThreatNG",
    "Visible Risk",

    # --- Additional MSSPs / MDR ---
    "ActZero",
    "Antigen Security",
    "Cato MDR",
    "CFC Underwriting",
    "CyFlare",
    "DataEndure",
    "Foresite Cybersecurity",
    "GoSecure",
    "Gradient Cyber",
    "GreenPages",
    "Huntress MDR",
    "Ingalls Information Security",
    "Iron Bow",
    "LevelBlue",
    "Netsurion MDR",
    "SilverSky",
    "SOCSoter",
    "Stratejm",
    "Tata Consultancy Services Cyber",
    "Trustwave MDR",
    "Vijilan Security",
    "Wipro Cybersecurity",

    # --- Additional Training / Simulation ---
    "Avatao",
    "Hack The Box",
    "HackEDU",
    "Immersive Labs",
    "PentesterLab",
    "PlexTrac Training",
    "RangeForce",
    "Secureflag",
    "Security Innovation",
    "TryHackMe",

    # --- Additional Antivirus / Consumer Security ---
    "Avast",
    "AVG",
    "Avira",
    "BullGuard",
    "Dr.Web",
    "G Data",
    "K7 Security",
    "Panda Security",
    "PC Matic",
    "Quick Heal",
    "Sophos Home",
    "TotalAV",
    "Trend Micro Home",
    "Webroot SecureAnywhere",
    "ZoneAlarm",

    # --- Additional Network Security ---
    "AlgoSec",
    "Arista",
    "Barracuda Networks",
    "Cisco SecureX",
    "Extreme Networks Security",
    "Flowmon Networks",
    "Fortinet FortiManager",
    "Fortinet FortiAnalyzer",
    "ManageEngine Firewall Analyzer",
    "NetBrain",
    "Palo Alto Panorama",
    "RedSeal",
    "Skybox Security",
    "WhatsUp Gold",

    # --- Additional GRC / Risk ---
    "CyberStrong",
    "Diligent Governance",
    "Isora GRC",
    "Navex Global",
    "NIST CSF Tools",
    "Ostendio",
    "RiskWatch",
    "Secuvant",
    "ServiceNow Risk",
    "Tandem",
    "ZenRisk",

    # --- Devsecops / CI CD Security ---
    "Argon Security",
    "Bitninja",
    "BoxyHQ",
    "Buildkite Security",
    "CircleCI Security",
    "CloudBees",
    "Escape",
    "Fianu Labs",
    "Garnet Labs",
    "Grit",
    "Krane",
    "Moderne",
    "Rego Security",
    "Seal Security",
    "Wabbi",

    # --- Cloud Security Posture Management (standalone) ---
    "C3M Cloud Control",
    "CSPM Aqua",
    "DivvyCloud",
    "Horangi",
    "HyperCloud Security",
    "Kion",
    "Lacework CSPM",
    "nOps",
    "Orca CSPM",
    "Paladin Cloud",
    "Tenable CSPM",
    "Uptycs CSPM",

    # --- Additional Zero Trust ---
    "Agilicus",
    "Cyolo",
    "Enclave Networks",
    "Mesh Security",
    "NetFoundry",
    "OpenZiti",
    "Portnox Zero Trust",
    "Tempered Networks",
    "ZPE Systems",
    "Zscaler Zero Trust",

    # --- Security Orchestration ---
    "Demisto",
    "InsightConnect",
    "Phantom",
    "Phantom (Splunk)",
    "Pliant",
    "Rapid7 SOAR",
    "Securonix SOAR",
    "Splunk Phantom",
    "StackStorm",
    "Swimlane Turbine",
    "XSOAR",

    # --- Web Security / Content Filtering ---
    "Barracuda Web Security",
    "ContentFilter",
    "Cyren",
    "Fortinet FortiWeb",
    "GFI WebMonitor",
    "Lightspeed Systems",
    "Smoothwall",
    "Sophos Web",
    "Websense",

    # --- Vulnerability Disclosure / Bug Bounty ---
    "Bugcrowd VDP",
    "Cobalt VDP",
    "Federacy",
    "HackerOne VDP",
    "Intigriti",
    "Open Bug Bounty",
    "Synack VDP",
    "YesWeHack",
    "Yogosha",

    # --- Additional IoT Security ---
    "Asimily",
    "BG Networks",
    "Claroty xDome",
    "CyberMDX",
    "Device Authority",
    "Finite State",
    "Keyfactor IoT",
    "Medigate by Claroty",
    "MicroSec",
    "Ordr",
    "Phosphorus",
    "SecuriThings",
    "Shield-IoT",
    "Sternum",
    "Thistle Technologies",
    "VDOO",
    "Viakoo",
    "Xage Security",
    "ZingBox",

    # --- Deepfake / Social Engineering Defense ---
    "AI Shield",
    "Attestiv",
    "Pindrop",
    "Resemble AI",
    "Truepic",

    # --- Secure Development Platforms ---
    "GitGuardian",
    "GitHub Copilot Security",
    "Guardrails AI",
    "LGTM",
    "Mobb",
    "Nullify",
    "Qwiet AI",
    "Semgrep Cloud",
    "Snyk Developer",
    "Sonar Developer",
    "Spacelift",
    "Tromzo Security",

    # --- Data Classification ---
    "Boldon James",
    "Classifier360",
    "Fortra",
    "Janusnet",
    "Spirion Data Classification",
    "Titus",
    "Varonis Classification",

    # --- Managed Vulnerability Services ---
    "Edgescan",
    "NopSec Platform",
    "Outpost24",
    "Rapid7 Managed VM",
    "Tenable Managed",
    "Vuln Manager",

    # --- Security Operations Center (SOC) Tools ---
    "DFLabs",
    "Exabeam SOC",
    "IBM QRadar SOC",
    "LogRhythm SOC",
    "Microsoft Sentinel SOC",
    "SOCFortress",
    "Splunk Mission Control",

    # --- Encryption / Tokenization ---
    "Anjuna Security",
    "Enveil",
    "Fortanix",
    "Futurex",
    "Ionic Security",
    "Micro Focus Voltage",
    "PreVeil Encryption",
    "ShardSecure",
    "Thales Encryption",
    "TokenEx Encryption",
    "Vault12",
    "Virtru Encryption",
    "Wickr Enterprise",

    # --- Access Management / SSO ---
    "Centrify SSO",
    "Citrix Workspace",
    "Duo SSO",
    "FusionAuth",
    "Janrain",
    "Keycloak",
    "LastPass Identity",
    "Microsoft SSO",
    "Okta SSO",
    "OneLogin SSO",
    "PingFederate",
    "Shibboleth",

    # --- Runtime Application Self-Protection (RASP) ---
    "Contrast RASP",
    "Dynatrace RASP",
    "Hdiv Security",
    "Imperva RASP",
    "Micro Focus RASP",
    "OpenRASP",
    "Prevoty",
    "Signal Sciences RASP",
    "Sqreen",
    "Waratek",

    # --- Security Consulting Firms ---
    "Bishop Fox",
    "Booz Allen Hamilton Cyber",
    "Coalfire Security",
    "Crowdstrike Services",
    "CyberProof",
    "Deloitte Cyber Advisory",
    "EY Cybersecurity",
    "FireEye Mandiant",
    "GuidePoint Security",
    "Kroll Cyber",
    "Mandiant Consulting",
    "NCC Group Consulting",
    "NetSPI Consulting",
    "NTT DATA Security",
    "Optiv Security",
    "Protiviti Cybersecurity",
    "PwC Cybersecurity",
    "Rapid7 Services",
    "Secureworks Advisory",
    "Trustwave Consulting",

    # --- Cyber Range / Training Platforms ---
    "AttackIQ Academy",
    "CYRIN",
    "Infosec Skills",
    "NICE CyberRange",
    "Offensive Security (OffSec)",
    "PCYSYS",
    "Raytheon Cyber Academy",
    "SimSpace",
    "Without Limits",

    # --- Hardware / Physical Security ---
    "Axis Communications",
    "Cisco Physical Security",
    "Genetec",
    "HID Global",
    "Honeywell Security",
    "Lenel",
    "LenelS2",
    "Milestone Systems",
    "Verkada",

    # --- Additional Compliance Automation ---
    "Accountable",
    "Apptega",
    "CalCom",
    "ComplyAdvantage",
    "Corporater",
    "ISMS.online",
    "JupiterOne Compliance",
    "Kanaries",
    "Redstor",
    "SecureFrame Platform",
    "Security Studio",
    "SmartSuite",
    "TrustLayer",
    "Zluri",

    # --- Patch Management ---
    "Action1",
    "Automox Patch",
    "GFI LanGuard",
    "Ivanti Patch",
    "ManageEngine Patch Manager",
    "NinjaOne Patch",
    "PDQ Deploy",
    "Qualys Patch Management",
    "SolarWinds Patch Manager",
    "Tanium Patch",

    # --- SaaS Security / Shadow IT ---
    "Avepoint",
    "BetterCloud",
    "CloudKnox SaaS",
    "Megazone",
    "Netskope SaaS",
    "ProductBoard Security",
    "Torii",
    "Zylo",

    # --- Non-Human Identity / Machine Identity ---
    "Aembit Machine Identity",
    "Astrix Machine Identity",
    "CyberArk Machine Identity",
    "HashiCorp Machine Identity",
    "Spiffe",
    "Venafi Machine Identity",

    # --- Additional Vendors (Comprehensive coverage) ---
    "1Kosmos",
    "6clicks",
    "Acalvio Shadow Plex",
    "Acreto",
    "ActiveFence",
    "AdaptiveMobile Security",
    "AET Europe",
    "AgileBlue",
    "AirgapFlowFence",
    "AirMagnet",
    "AlienVault USM",
    "Allgress",
    "Alsid",
    "Ami",
    "Anchore Grype",
    "Anomalix",
    "Anvilogic",
    "Aperture Data Studio",
    "AppGate SDP",
    "AppSec Labs",
    "AppSecEngineer",
    "Arete Incident Response",
    "Atakama",
    "AuthN by IDEE",
    "Awake Security",
    "Baramundi",
    "Bastille Networks",
    "Bay Dynamics",
    "BeyondID",
    "Black Duck Software",
    "Black Lantern Security",
    "Blancco",
    "Blink Security",
    "BlockAPT",
    "Blu Ventures",
    "BMC Helix",
    "Boole Server",
    "Bora Design",
    "BoxCryptor",
    "BreachLock",
    "Bugprove",
    "Bugsnag",
    "C3 AI Security",
    "Canary",
    "CardinalOps",
    "Caveonix",
    "CAWS",
    "Certes Networks",
    "Cider Security",
    "CloudVector",
    "Cofense Triage",
    "Cog Systems",
    "ComplyCloud",
    "Corellium",
    "Cortex Data Lake",
    "CrowdSec",
    "Crypto Quantique",
    "CryptoStopper",
    "Curtail Security",
    "Cybellum",
    "CyberArk Identity",
    "CyberArk Workforce Identity",
    "CyberCatch",
    "CyberFortress",
    "CyberMaxx",
    "CyberOwl",
    "CyberPoint",
    "CyberQ Group",
    "CyberReady",
    "CyberSixgill",
    "CyberSmart",
    "CyberSponse",
    "Cyborg HAWK",
    "Cycurio",
    "Cynomi",
    "Cyren",
    "Dashlane Business",
    "Datavisor Platform",
    "DefendEdge",
    "Delinea Server Suite",
    "DeviceTotal",
    "DigitalStakeout",
    "DisruptOps",
    "DNStwist",
    "DuoKey",
    "Dynatrace Security",
    "Eclypsium",
    "Edgewise Networks",
    "EiQ Networks",
    "Elk Analytics",
    "Endace",
    "Endpoint Security (generic)",
    "Enzoic",
    "Evolve IP",
    "ExeonTrace",
    "Farsight Security",
    "Feroot Security",
    "FingerprintJS",
    "FireCompass",
    "FireEye",
    "Fixify",
    "Fletch",
    "Fortalice Solutions",
    "Fortanix Runtime",
    "FortMesa",
    "Frsecure",
    "Garland Technology",
    "GGIP Group",
    "GitSecretScanner",
    "GlassWire",
    "GoodAccess",
    "Green Hills Software",
    "Hacken",
    "HackNotice",
    "HAProxy",
    "HawkEye",
    "Helios",
    "Herjavec Security",
    "Hexway",
    "Honeynet Project",
    "Hunchly",
    "HyperGrid",
    "Hysolate",
    "IEC62443",
    "ImmersiveFusion",
    "Infrared Security",
    "Inner Range",
    "InsightConnect",
    "IntSights",
    "iProov",
    "IRONSCALES Complete",
    "IronWASP",
    "iStorage",
    "Ixia",
    "Jask",
    "Javelin Networks",
    "JFrog",
    "Karambit.AI",
    "Keysight",
    "Knownsec",
    "Lacework Polygraph",
    "LimaCharlie",
    "LogSentinel",
    "Lucidum",
    "Lumeus",
    "Lumu",
    "MagicCube",
    "MainNerve",
    "ManageEngine EventLog Analyzer",
    "ManageEngine Firewall",
    "Mandiant Threat Intelligence",
    "Mati",
    "MDSec",
    "Miradore",
    "Morphisec",
    "Myki",
    "Nessus Professional",
    "NetCentrics",
    "Netcraft",
    "NetDiligence",
    "NetMotion",
    "Netography",
    "Netwrix",
    "Netwrix Auditor",
    "NeuShield",
    "NextDLP",
    "NIST",
    "Nisos",
    "Noetic Cyber",
    "Norsk Hydro Cyber",
    "Obsidian SSPM",
    "Omada Identity",
    "OnDefend",
    "OneSpan Sign",
    "Ontinue",
    "Opaq Networks",
    "Orion Security",
    "OXO Security",
    "PaloAlto DNS Security",
    "PatrowlHears",
    "Pcap",
    "Phosphorus IoT",
    "Plextrac Platform",
    "Point Wild",
    "Prey",
    "ProArch",
    "ProcessBolt AI",
    "PurpleSec",
    "Qomplx",
    "Qualys CloudView",
    "Quasar",
    "QueryAI",
    "QuoLab",
    "R-Vision",
    "RackTop Systems",
    "RAMP",
    "Raxis",
    "ReaQta",
    "Remediant",
    "Revision Legal",
    "RevBits",
    "ReverseVPN",
    "Rhino Security Labs",
    "Rivetz",
    "RocketCyber",
    "RootSecure",
    "Runsafe Security",
    "S21sec",
    "SafeGuard Cyber",
    "SAM Seamless Network",
    "SAP Security",
    "SCADAfence Platform",
    "Scalarr",
    "Scythe Platform",
    "SecBI",
    "Secret Double Octopus",
    "SecureStack",
    "SecureW2",
    "SecurityBridge",
    "SecurityStudio",
    "Semperis AD",
    "SenRa",
    "Sepio",
    "SeverStal Security",
    "ShiftControl",
    "SiemensXHQ",
    "Silobreaker",
    "Skydio",
    "SlashID",
    "SmartContract Security",
    "Snorkel AI Security",
    "SOC Prime",
    "Socure Identity",
    "SonicWall Email",
    "Sontiq",
    "SpecterOps",
    "Spirion Privacy",
    "Spire Solutions",
    "Splunk Intelligence Management",
    "SUSE Rancher Security",
    "TalonWork",
    "Tamnoon",
    "TechDemocracy",
    "Tenable Lumin",
    "Tenable OT",
    "TeraByte",
    "Thinkst Canary",
    "ThreatGEN",
    "ThreatModeler",
    "ThreatSpike",
    "Titaniam",
    "TokenEx Gateway",
    "Tonic.ai",
    "TorGuard",
    "Traceable Platform",
    "Trellix XDR",
    "TrendMicro XDR",
    "Triaxiom Security",
    "TrueStack",
    "TruKno",
    "Truvantis",
    "Tugboat Security",
    "Tychon",
    "UAM Security",
    "UberAgent",
    "Uila",
    "Uniqkey",
    "USM Anywhere Platform",
    "VaultOne",
    "Vericlouds",
    "Versa Director",
    "Viavi",
    "Vigilante",
    "Virsec",
    "Visium",
    "Vorlon",
    "Votiro",
    "Vultara",
    "Wib Security",
    "Xceedance",
    "Xoriant Security",
    "Yextend",
    "Zentera",
    "Zercurity",
    "Zimperium zIPS",

    # --- Additional Vendors (Ensure 3000+) ---
    "3CORESec",
    "7Elements",
    "802 Secure",
    "Abnormal Platform",
    "Abstract Security",
    "Acceptto",
    "AccessOwl",
    "AcuSense",
    "Adallom",
    "Aegis Security",
    "Aerodefense",
    "AgileBlue SOC",
    "AIDASH Security",
    "Aker Security",
    "AlienApp",
    "Altitude Networks",
    "Anchore Inline",
    "Angoka",
    "Ansys Security",
    "Anubis",
    "AnyVision",
    "AppCheck",
    "AppDome Mobile",
    "Appsian",
    "AppSolid",
    "Approov",
    "Aqua DTA",
    "Arcturus",
    "Ardent Privacy",
    "ArmorCode",
    "ArmorText",
    "Ascend Technologies",
    "Aserto",
    "ASG Technologies",
    "ASPIA InfoTech",
    "Assured Enterprises",
    "AsTech Consulting",
    "Atos Cybersecurity",
    "Attivo Deception",
    "Aurora Systems Consulting",
    "AutoRABIT Security",
    "Ava Security",
    "Avocado Systems",
    "BalkanID",
    "Barracuda MSP",
    "Basis Technology",
    "Bayshore Industrial",
    "Bedrock Security",
    "BforeAI",
    "BigPanda",
    "Binary Defense MDR",
    "Binarly",
    "BioConnect",
    "BioSig Technologies",
    "BitDam",
    "BitNinja",
    "Blackberry CylancePROTECT",
    "Blackbird AI",
    "Blackwell Security",
    "Blue Cedar",
    "Blue Coat",
    "Blue Hexagon",
    "Blue Lava",
    "BluBracket",
    "Blueshift Cybersecurity",
    "Bluink",
    "BoostSecurity",
    "Bridewell",
    "BTB Security",
    "Bugherd",
    "C1 Security",
    "Calian Cyber",
    "Canonic Security",
    "Cape Privacy",
    "Carceron",
    "CCM Security",
    "Censinet",
    "CentricMinds",
    "Cerberus Sentinel",
    "Certes",
    "Certo",
    "Chalk Mountain",
    "Chimera Security",
    "Cigent",
    "Cisco Kenna Security",
    "Cisco Talos",
    "CivicPlus",
    "Cleafy",
    "ClearDATA",
    "ClearVector",
    "ClouDNS",
    "CloudeAssurance",
    "CloudMask",
    "CloudSEK",
    "CloudSOC",
    "Clumio Cloud",
    "CODA Intelligence",
    "Code Intelligence",
    "Codelock",
    "Cognito",
    "Colt Cyber",
    "Comcast Business Security",
    "Command Zero",
    "ComplianceForge",
    "CompliancePoint",
    "Comtech",
    "ConfigOS",
    "Confluera",
    "Constella Intelligence",
    "Copado Security",
    "Coralogix",
    "Cork Protection",
    "CortexPrime",
    "CoverMyMeds Security",
    "Craw Security",
    "CrossPoint Capital",
    "CrowdStrike Humio",
    "Crypteron",
    "CryptoMove",
    "Cujo AI",
    "Cure53",
    "Curtiss-Wright Defense",
    "CybelAngel",
    "CyberCX",
    "CyberFOX",
    "CyberHat",
    "CyberInt",
    "CyberKnight",
    "CyberPion",
    "CyberRes",
    "CyberScoop",
    "CybersecAsia",
    "CyberVadis",
    "CybrHawk",
    "CyCraft",
    "CyFIR",
    "CyGlass",
    "Cymptom",
    "CyNtec",
    "Cypago",
    "Cyrebro",
    "CyScope",
    "DarkOwl",
    "Dasgate",
    "DataFleets",
    "DataKitchen",
    "DataLocker",
    "DataTribe",
    "DatAnswers",
    "DattoCon",
    "Debricka",
    "Deduce Identity",
    "Deepcode",
    "DeepInfo",
    "DeepSurface",
    "DeepWatch Platform",
    "Delinea DevOps",
    "Detexian",
    "DevOcean",
    "DigiSec360",
    "Discern Security",
    "DoubleVerify",
    "Dovecot",
    "Drawbridge",
    "Druva inSync",
    "Dtex InTERCEPT Pro",
    "Duo Beyond",
    "Dusk Network",
    "e-Safe Compliance",
    "E8 Security",
    "Eagle Eye Networks",
    "EagleView Security",
    "Ebryx",
    "Eclypsium Platform",
    "ElevenPaths",
    "EliteSec",
    "Embodied Intelligence",
    "Emsisoft Business",
    "Endgame",
    "Endor",
    "Ensighten",
    "Enterprise Immune System",
    "Eperi",
    "Epiq",
    "Ermetic CIEM",
    "Ethyca Fides",
    "Eurotech",
    "EventTracker",
    "Eviden",
    "Evident Security",
    "Exabeam Platform",
    "ExcelForce",
    "Exein IoT",
    "Exium",
    "ExpressVPN",
    "Extenua",
    "Eye Security",
    "F5 Shape",
    "F5 Distributed Cloud",
    "Falcon LogScale",
    "FalconStor",
    "FieldEffect Covalence",
    "FileCloud",
    "Finsec Innovation Lab",
    "FireLayers",
    "FirstPoint Mobile Guard",
    "Fishtech",
    "Flare.io",
    "FlexibleIR",
    "Fognigma",
    "Forcepoint CASB",
    "ForceShield",
    "Foresiet",
    "FortiProxy",
    "Fortscale",
    "FoxGuard",
    "FPT Security",
    "Fugue Platform",
    "GajShield",
    "Gamma",
    "GBProtect",
    "GCA Automated IoT Defence",
    "Gem Security",
    "Geobridge",
    "GetVisibility",
    "Glasswire Firewall",
    "Glasswall",
    "GlobalPlatform",
    "GlowRoot",
    "Glycon",
    "GoSecure Platform",
    "Green Radar",
    "GreenRope",
    "GroupSense",
    "Guardicore Platform",
    "Guardio",
    "Guardium Insights",
    "Guardsquare",
    "Gutsy Platform",
    "HackEDU Platform",
    "HackuityPlatform",
    "Halborn",
    "Halcyon Tech",
    "HarfangLab",
    "Hawk AI",
    "Haystax",
    "Heimdal Security",
    "Helidon Security",
    "HelpSystems",
    "HighGround",
    "HighSide",
    "Hornetsecurity 365",
    "HoxHunt Platform",
    "HUB Security",
    "Hubble Technology",
    "HumanFirewall",
    "Huntsman Security",
    "HyperVerge",
    "Hypr",
    "iC Consult",
    "ID.me",
    "IDmachines",
    "Igloo Security",
    "Immersive Labs Platform",
    "Immunefi",
    "ImpactCyber",
    "Imperva Bot",
    "Incapsula",
    "InfiniDome",
    "Infocyte",
    "InfoSecIQ",
    "InfraGard",
    "Ingrian Networks",
    "Inspectiv",
    "IntegriCom",
    "Intelligent Waves",
    "IntSights Threat Intelligence",
    "IOActive",
    "IriusRisk",
    "ISC2",
    "Ivalua Security",
    "Ivanti Application Security",
    "JasonHelman",
    "Jemurai",
    "Jscrambler",
    "Kameleon Security",
    "Keeper Business",
    "Keisuke Security",
    "Keyvi",
    "KnectIQ",
    "Koide Technology",
    "Kolide",
    "Kratikal",
    "Kroll Cyber Risk",
    "KryptoKloud",
    "Kustodian",
    "KYND",
    "Lansweeper Security",
    "Lasso Security Platform",
    "LayerX Security",
    "Leviathan Security",
    "LexisNexis Risk Solutions",
    "LimaCharlie Cloud",
    "Liongard",
    "Living Security Platform",
    "LogMeIn Security",
    "Lumifi Cyber",
    "Lynx Technology",
    "Magnet AXIOM",
    "ManagedMethods",
    "Mandiant Automated Defense",
    "Mango Security",
    "Mantis",
    "Mato Security",
    "MazeBolt",
    "McAfee Enterprise",
    "MedCrypt",
    "Memcyco",
    "Menaya",
    "Metallic",
    "MetaCert",
    "MicroFocus ArcSight",
    "Minerva Labs",
    "Mirach",
    "Mitiga",
    "MixMode",
    "Mobix Communications",
    "Morpheus Data",
    "MotherBoard",
    "N-able",
    "NAXSI",
    "Nebulon",
    "NEO4J Security",
    "Nessus Expert",
    "Netacea Bot",
    "NetFort",
    "NetFoundry Zero Trust",
    "Netography Platform",
    "Netrise",
    "Netskope Private Access",
    "NetSPI Platform",
    "Neustar Security",
    "Next DLP Reveal",
    "NightDragon",
    "Nipper",
    "Normalyze Platform",
    "NorthRow",
    "NotSoSecure",
    "NovaBACKUP",
    "Nucleon Security",
    "NXLog",
    "OctoXLabs",
    "OneTrust Technology Risk",
    "Ontic",
    "Open Raven Platform",
    "OpenBAS",
    "OpenText Fortify",
    "Operative Intelligence",
    "Opsview",
    "Opticks",
    "Oracle Cloud Guard",
    "Oracle Data Safe",
    "Orca Runtime",
    "Osirium",
    "OwlGaze",
    "OXO Solutions",
    "PacketFabric",
    "PacketTotal",
    "Palantir Cyber",
    "Palo Alto Unit 42",
    "Pandora FMS",
    "Paraflare",
    "Pathlock",
    "PatrOwl",
    "PCAP Analysis",
    "Peckshield",
    "Pensar",
    "Perch MDR",
    "PhishCloud",
    "PhishLine",
    "Phriendly Phishing",
    "Piiano Privacy",
    "Plaid Security",
    "PlainID",
    "Plurilock",
    "PortDiver",
    "PostSwigger Web Security",
    "Prevalent AI",
    "Prey Device Management",
    "Prism Infosec",
    "Privacy Analytics",
    "PrivacyOps",
    "Probely Scanner",
    "Proficio MDR",
    "ProofID",
    "Proton VPN",
    "Protexxa",
    "Pureport",
    "Qintel",
    "QualysGuard",
    "QuarksLab",
    "RackWare",
    "Radiflow Platform",
    "Rapid7 AppSec",
    "Rapid7 MDR",
    "Rapid7 Velociraptor",
    "RapidFort",
    "Red Balloon Security",
    "Red Canary MDR",
    "Red Hat Security",
    "Red Sift",
    "Redacted",
    "Redscan",
    "Regal Voice Security",
    "Relyance AI",
    "ReSec Technologies",
    "Resecurity",
    "RetireJS",
    "Returnal Security",
    "Rewterz",
    "Ribbon Communications",
    "Ridgeback Network Defense",
    "Riot Security",
    "Ripjar",
    "RNDR Security",
    "Rockwell Collins Cyber",
    "RocketCyber Platform",
    "Rohde & Schwarz Cybersecurity",
    "RSI Security",
    "RunSafe Security Platform",
    "Rutoken",
    "S1 Security",
    "SAFECode",
    "SAINT Security",
    "Salus Security",
    "Samurai Digital Security",
    "SandboxAQ Encryption",
    "SandFly Security",
    "Sangfor Cyber Command",
    "Sans Technology Institute",
    "Saporo",
    "SaviyntIGA",
    "SCADA Fence",
    "Scandit",
    "Scantist",
    "SciTokens",
    "Scout",
    "Scutum",
    "Sealand Cyber",
    "SecBI Autonomous",
    "SecludIT",
    "Secnap",
    "SecOps Group",
    "SecPod",
    "SecretHub",
    "Secrets Rotation",
    "SecureBridge",
    "SecureCircle",
    "SecureFlag Platform",
    "SecureIQLab",
    "SecureLayer7",
    "SecureLink",
    "SecurelyShare",
    "SecureMac",
    "SecurEnds",
    "Securiti Data Command",
    "SecurityAdvisorMe",
    "SecurityHQ",
    "SecurityIntelligence",
    "SecurityJoes",
    "Securityweek",
    "SEConion",
    "Sectigo CMS",
    "SeeMetrics",
    "Segugio",
    "SekurSafe",
    "Semmle",
    "SenCy Cyber",
    "Senhasegura PAM",
    "SentinelLabs",
    "Sepio Systems",
    "ServerScan",
    "Seventy2 Cybersecurity",
    "Sevket",
    "Shadow Security",
    "Shield AI",
    "ShieldIO",
    "Sigmaflow",
    "SilverBullet",
    "SimpleLogin",
    "Siren",
    "SirenJack",
    "SiteLock",
    "SlashID Identity",
    "SmartHive",
    "Smokescreen",
    "Snoopwall",
    "Snowbit",
    "SOC Radar Platform",
    "SOCAutomation",
    "SoDA",
    "SonicWall Capture",
    "SonicWall SecureFirst",
    "Sophos XDR",
    "Sounil Yu",
    "SourceClear",
    "Specops Software",
    "SpireSec",
    "Splunk Attack Analyzer",
    "SpotBugs",
    "StackPath",
    "StealthBits",
    "Sternum IoT",
    "StoneFly",
    "Stormforge",
    "Strongbox IT",
    "Stuff Security",
    "Sudo Security",
    "SurfControl",
    "Swarmnetics",
    "Swimlane Platform",
    "SynerComm",
    "Synopsys SIG",
    "Synthrone",
    "Sysdig Monitor",
    "SysTools",
    "Taegis XDR",
    "TalosIntelligence",
    "TAPA",
    "Tauruseer",
    "TealTech",
    "Techtarget Security",
    "TeleCommunity",
    "Tenable Attack Surface",
    "Tenable.asm",
    "Teramind DLP",
    "Tessera Security",
    "Tetrate",
    "Thirdwave",
    "ThisIsMe",
    "ThreatAdvice",
    "ThreatCast",
    "ThreatHunter.ai",
    "ThreatKey",
    "ThreatLocker Platform",
    "ThreatMark",
    "ThreatStop",
    "ThreatWar",
    "TinfoilMe",
    "TippingPoint",
    "Todyl Platform",
    "TraceLink",
    "Trellix Platform",
    "Trend Micro TippingPoint",
    "TriageSec",
    "Trident",
    "Trinity Cyber",
    "TruNarrative",
    "TrustLogix",
    "TrustwaveSIEM",
    "Trustworthy",
    "TufinSecureCloud",
    "Turbine Labs",
    "TuringSense",
    "Twistlock Platform",
    "Ubiqu",
    "Unico Identity",
    "Unified Security",
    "UnifyID",
    "Untitled Security",
    "Ursa Major",
    "Usercube",
    "Utaku",
    "ValenceDefense",
    "ValtixSecurity",
    "Vectra Platform",
    "VenafiTrust Protection",
    "Verimatrix",
    "VersaONE",
    "Veza Identity",
    "Vicarius",
    "Virtana",
    "Virtuespark",
    "VisibleRisk Platform",
    "Vistara IT",
    "Vivint Smart Home Security",
    "Voxility",
    "Vulcan Cyber Risk",
    "Vulners",
    "WallixBastion",
    "WatchTower Security",
    "WebPurify",
    "Whitecryption",
    "WhiteHat Security",
    "Widevine",
    "Windscribe",
    "WiseSec",
    "Wombat Proofpoint",
    "Wordfence Security",
    "XDR Platform",
    "Xebia Security",
    "Xplain",
    "Xybion",
    "Yandex Security",
    "Yotascale",
    "Zafran",
    "Zapata Computing Security",
    "ZecOps",
    "Zenoss",
    "ZeroTier",
    "ZeroTrust Guard",
    "Zinc Security",
    "Zivver",
    "ZKX Security",
    "Zonefox",
    "ZPE Cloud",
    "Zyston",

    # --- Additional Vendors Batch 2 (Reaching 3000+) ---
    # More YC security companies
    "Airgraft Security",
    "Akto",
    "Bearer Security",
    "Bunkyr",
    "Canopy",
    "Certa",
    "CommandK",
    "Corgea",
    "Crosshatch",
    "CyberLeap",
    "CyberPeace",
    "DeepSeas",
    "Detectify",
    "Dover Microsystems",
    "DuskRise",
    "Encrypt.me",
    "Enso Security Platform",
    "Fides",
    "Fleet DM",
    "Footprint",
    "Freq",
    "Gomboc AI",
    "Grep Security",
    "Hallci",
    "Havoc Shield",
    "Hopr",
    "Indent",
    "Inspector",
    "Jericho Security",
    "Kintent",
    "Lattice Security",
    "Livereach",
    "Manifest Security",
    "Materialise Security",
    "MergeBase",
    "Monad Security",
    "Naq Cyber",
    "NightVision",
    "Normalyze AI",
    "Optery",
    "Ozone Security",
    "Paladin Cyber",
    "Prelude Security",
    "Prompt Armor",
    "Qrypt",
    "Resurface.io",
    "Salt AI",
    "Sandfly",
    "Securin",
    "Shift5",
    "Soteri",
    "Soveren",
    "Stacklet",
    "Stairwell",
    "Stretch Security",
    "Tidal Cyber",
    "Truffle Security",
    "TrustElements",
    "Uptycs Platform",
    "Valarian",
    "Veraison",
    "Veriti",
    "Veza Platform",
    "Vorpal",
    "Wabbi Security",
    "Xygeni",
    "Zafran Security",
    "Zenity",

    # More SIEM / Log vendors
    "Anvilogic SIEM",
    "Bindplane",
    "Blumira SIEM",
    "CardinalOps SIEM",
    "Coralogix SIEM",
    "Fluentd",
    "Logstash",
    "Matano",
    "Panther Labs",
    "RunReveal",
    "Tenzir",
    "Vector",
    "Wazuh SIEM",

    # More EDR / Endpoint
    "Acreto Security",
    "Airlock Digital",
    "Applocker",
    "Carbon Black Cloud",
    "ConnectWise Endpoint",
    "Cortex XDR Pro",
    "CylancePROTECT",
    "DeepArmor",
    "Elastic Endpoint",
    "Fortinet FortiClient EMS",
    "Intezer Analyze",
    "Limacharlie EDR",
    "Microsoft Defender Antivirus",
    "Morphisec Guard",
    "Sangfor Endpoint Secure",
    "SecureAge",
    "SentinelOne Purple AI",
    "Symantec SEP",
    "ThreatDown EDR",
    "Trellix ENS",
    "Trend Micro Apex One",
    "Vinchin",

    # More WAF / Web Security
    "AppTrana",
    "Bekchy",
    "Cloudbric",
    "Comodo cWatch",
    "DenyAll",
    "Edgecast WAF",
    "F5 NGINX App Protect",
    "FortiWeb",
    "HAProxy Enterprise",
    "Imunify360",
    "Incapsula WAF",
    "KeyCDN",
    "NSFOCUS WAF",
    "Open-Appsec",
    "Prophaze WAF",
    "Qualys WAF",
    "Reblaze WAF",
    "SafeLine WAF",
    "Shadow Daemon",
    "StackPath WAF",
    "Wallarm WAAP",
    "WebKnight",

    # More GRC / Compliance
    "6clicks GRC",
    "Archer GRC",
    "BitSight GRC",
    "Camms GRC",
    "ComplianceQuest",
    "ConnectSmart GRC",
    "CyberSaint RiskQ",
    "Eramba",
    "Galvanize HighBond",
    "Governica",
    "HighBond",
    "iGRC",
    "Isora",
    "MasterControl",
    "MetricStream GRC",
    "Mitratech",
    "NAVEX",
    "Ncontracts",
    "OnSpring",
    "PrivacyEngine",
    "ProcessMAP",
    "Protecht",
    "QualityKick",
    "Quantivate GRC",
    "Resolver GRC",
    "RiskOptics",
    "SAI Global",
    "ServiceNow IRM",
    "Sword GRC",
    "Symbiant",
    "ThirdPartyTrust",
    "TruOps",
    "Workiva",
    "ZenRisk Platform",

    # More Vulnerability Scanners
    "Arachni",
    "BurpSuite Pro",
    "Censys ASM",
    "CloudSploit",
    "Detectify Scanner",
    "HackerTarget",
    "HostedScan",
    "Intruder Scanner",
    "Lynis Scanner",
    "Nessus Expert Scanner",
    "Nuclei Scanner",
    "Outpost24 Scanner",
    "PingSafe Scanner",
    "Probely Scanner Pro",
    "Retina Scanner",
    "Skipfish",
    "Striker",
    "W3af Scanner",
    "Wapiti",

    # More Identity / MFA
    "AuthSignal",
    "Beyond Identity",
    "CIAM Platform",
    "Cisco Duo MFA",
    "Daon",
    "FEITIAN",
    "FusionAuth Identity",
    "GateKeeper",
    "Hideez",
    "HyperVerge Identity",
    "IDEE",
    "Keystone Identity",
    "Nok Nok Labs",
    "PingID",
    "RSA SecurID",
    "SecureAuth Identity",
    "Thales OneWelcome",
    "Trusona",
    "TypingDNA",
    "Verifiable",
    "Yubico Authenticator",

    # More MDR / MSSP
    "ActZero MDR",
    "Atos MDR",
    "BAE Systems Digital Intelligence",
    "Capgemini Cybersecurity",
    "Cipher Security",
    "ControlScan",
    "Cybereason MDR",
    "CyberProof SOC",
    "DirectDefense",
    "FortressIQ",
    "Foresite MSS",
    "GreenPages MSS",
    "Infocyte MDR",
    "InteliSecure",
    "Kudelski Security",
    "LevelEffect",
    "Mandiant Managed Defense",
    "MOXFIVE",
    "Netox",
    "Novacoast",
    "Radius Security",
    "Reliance Cyber",
    "SilverSky Managed",
    "SolCyber",
    "Solis Security",
    "Sophos Central MDR",
    "Tenable Managed Security",
    "Trellix MDR",
    "WithSecure MDR",

    # More Network Security
    "AlgoSec Firewall",
    "Arbor Networks",
    "Aviatrix",
    "Barracuda Firewall",
    "Calico Enterprise",
    "Certes Networks Encryption",
    "Corelight Sensor",
    "Darktrace DETECT",
    "Darktrace RESPOND",
    "ExtraHop Reveal(x) 360",
    "Firemon Firewall",
    "ForeScout eyeSight",
    "FortiAnalyzer",
    "FortiManager",
    "Guardicore Centra",
    "Illumio Endpoint",
    "Ixia Network",
    "Keysight Network",
    "Nile Secure",
    "Opengear",
    "PacketFence",
    "Portnox Cloud",
    "Tufin Orchestration",
    "Vectra Detect",
    "VMware Avi",
    "Zentera CoIP",

    # More DevSecOps / ASPM
    "Apiiro ASPM",
    "ArmorCode ASPM",
    "Bionic ASPM",
    "Cycode ASPM",
    "Dazz Remediation",
    "Kondukto",
    "Legit ASPM",
    "OX ASPM",
    "Phoenix ASPM",
    "Plaxo Security",
    "Seeker IAST",
    "Semgrep SAST",
    "Snyk ASPM",
    "Synopsys Polaris",
    "Veracode Fix",
]

# Deduplicate and sort
VENDORS = sorted(set(VENDORS), key=str.casefold)
